//
//  LWPieChartDraw.swift
//  LWPieChart
//
//  Created by luowei on 2016/10/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class LWPieChartDraw : NSObject {

    //// Drawing Methods

    public class func drawPie( frame: CGRect = CGRect(x:0, y:0, width:120, height:120), color: UIColor = UIColor(red: 0.912, green: 0.611, blue: 0.407, alpha: 1.000), ratio: CGFloat = 1) {
        //// General Declarations
        guard let context = UIGraphicsGetCurrentContext() as CGContext? else{
            return
        }

        //// Color Declarations
        var colorHueComponent: CGFloat = 1,
            colorSaturationComponent: CGFloat = 1,
            colorBrightnessComponent: CGFloat = 1
        color.getHue(&colorHueComponent, saturation: &colorSaturationComponent, brightness: &colorBrightnessComponent, alpha: nil)

        let lightColor = UIColor(hue: colorHueComponent, saturation: 1, brightness: colorBrightnessComponent, alpha: color.cgColor.alpha)

        //// Variable Declarations
        let angle_exp: CGFloat = -ratio * 360
        let color_exp = ratio >= 0.75 ? lightColor : color

        //// Background Drawing
        let backgroundPath = UIBezierPath(ovalIn: CGRect(x:frame.minX + frame.width - 120, y:frame.minY + frame.height - 120, width:120, height:120))
        UIColor.gray.setFill()
        backgroundPath.fill()


        //// Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 0.50000 * frame.width, y: frame.minY + 0.50000 * frame.height)
        context.rotate(by: -90 * CGFloat(M_PI) / 180)

        let ovalRect = CGRect(x:-55, y:-55, width:110, height:110)
        let ovalPath = UIBezierPath()
        ovalPath.addArc(withCenter: CGPoint(x:ovalRect.midX, y:ovalRect.midY), radius: ovalRect.width / 2, startAngle: 0 * CGFloat(M_PI)/180, endAngle: -angle_exp * CGFloat(M_PI)/180, clockwise: true)
        ovalPath.addLine(to: CGPoint(x:ovalRect.midX, y:ovalRect.midY))
        ovalPath.close()

        color_exp.setFill()
        ovalPath.fill()

        context.restoreGState()
    }

}
