//
//  SinMotionDraw.swift
//  SinMotion
//
//  Created by luowei on 2016/10/17.
//  Copyright (c) 2016 wodedata. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SinMotionDraw : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(frame frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 120), x: CGFloat = 160) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let expression: CGFloat = 20 * sin(x * 5 * CGFloat(M_PI)/180) + 50

        //// Oval Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, (x + 10.5), (expression + 10.5))

        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: -10.5, y: -10.5, width: 21, height: 21))
        UIColor.greenColor().setFill()
        ovalPath.fill()

        CGContextRestoreGState(context)
    }

}
