//
//  LWProgressDraw.swift
//  LWProgressBar
//
//  Created by luowei on 2016/10/15.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class LWProgressDraw : NSObject {

    //// Drawing Methods

    public class func drawR(frame: CGRect = CGRect(x:0, y:0, width:300, height:16), progress: CGFloat = 83) {

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.361, blue: 0.000, alpha: 1.000)

        //// Progress Border Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(x:frame.minX + 1, y:frame.minY + 1, width:frame.width - 2, height:frame.height - 2), cornerRadius: (frame.height - 2)/2)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()

        
        //// Progress Activity Drawing
        let progressActivityPath = UIBezierPath(roundedRect: CGRect(x:1, y:1, width:progress, height:frame.height - 2), cornerRadius: (frame.height - 2)/2)
        color.setFill()
        progressActivityPath.fill()

        
        
//        //// General Declarations
//        guard let context = UIGraphicsGetCurrentContext() as CGContext? else{
//            return
//        }
//        
//        //// Image Declarations
//        let image = UIImage(named: "progressActivityImg.png")!
//        
//        //// Progress Activity Drawing
//        let progressActivityRect = CGRect(x:1, y:1, width:progress, height:frame.height - 2)
//        let progressActivityPath = UIBezierPath(roundedRect: progressActivityRect, cornerRadius: (frame.height - 2)/2)
//        context.saveGState()
//        progressActivityPath.addClip()
//        context.scaleBy(x: 1, y: -1)
//        context.draw(image.cgImage!, in: CGRect(x:progressActivityRect.minX, y:-progressActivityRect.minY, width:image.size.width, height:image.size.height), byTiling: true)
//        context.restoreGState()
    }

}
